### ISSUE TITLE
Markdown standards

### ISSUE THREAD

**Issue by mmoran0032** [PatrickMayoMoran/hello-world#2]
Many Markdown guides (e.g. [1][1]) require that headings be surrounded by blank lines. Additionally, if you want "Here I am!" and the following text as separate paragraphs

```diff
  # hello-world
+
  learning to use GitHub
```

[1]: https://www.markdownguide.org/basic-syntax

**Comment by PatrickMayoMoran** [comment]
I think I fixed it - Thanks!
